### ISSUE TITLE
Provide minified version

### ISSUE THREAD

**Issue by niutech** [louismerlin/concrete.css#14]
Please provide concrete.min.css

**Comment by louismerlin** [comment]
Yup, 100% agreed, PR incoming.

**Comment by louismerlin** [comment]
Latest version now includes [concrete.min.css](https://unpkg.com/concrete.css@2.1.2/concrete.min.css).

**Comment by niutech** [comment]
Thanks! Please also add `.min.css` to the README and docs.

**Comment by louismerlin** [comment]
Good point, I've pushed this to `main` 👍
