### ISSUE TITLE
Tweaks to the Home page examples

### ISSUE THREAD

**Issue by badcat** [louismerlin/concrete.css#6]
I like this.  However I noticed a couple of things that might benefit from some minor adjustments.

**Buttons:**
Per the W3C validation...

The `<button>` element must not appear as a descendant of the `<a>` element.

Suggest removing these examples:
```
<a href="./"><button>a link button</button></a>
<a href="./"><button disabled>a disabled link button</button></a>
```

**Break line:**
_Break line_ `<hr> `should probably be called _Horizontal Rule_.
Also, probably don't need to show `<hr />` with trailing slash for default html5, but instead just `<hr>`

**Comment by badcat** [comment]
@louismerlin I created a quick PR if it makes sense to merge?  Thanks for concrete.css

**Comment by louismerlin** [comment]
Very cool, thank you again for reporting 😄 

I'll be using these sorts of tools more regularly, I had never ran across them.
