### ISSUE TITLE
Stylesheet should allow for better layout

### ISSUE THREAD

**Issue by louismerlin** [louismerlin/concrete.css#9]
Right now concrete.css does not render well when using the following HTML layout:

```
<header>
</header>
<main>
</main>
<footer>
</footer>
```

This layout should be supported, and even potentially used by https://concrete.style/.

**Comment by hollisticated-horse** [comment]
whats the benefit of this layout over the other layout ?  less nesting ?

**Comment by louismerlin** [comment]
The inherent problem of the current layout is not nesting, it is that it is not the typical way the `header`, `main` and `footer` elements are arranged in a simple HTML document.

Adding support for this simpler layout will make *concrete* compatible by default with more pages without the need for any modification of the HTML document.

**Comment by louismerlin** [comment]
I've worked on this in the [no-resizing](https://github.com/louismerlin/concrete.css/blob/no-resizing) branch. The code is also available [in v3.0.0-next.0](https://unpkg.com/concrete.css@3.0.0-next.0/concrete.css).

**Comment by louismerlin** [comment]
Closed by #13.
